/**
 * The runtime config the browser reads, written by `scripts/build-runtime-config.mjs`.
 *
 * WHY THIS REPLACES A SERVER-SIDE READ
 *
 * The console began as server components: `src/lib/deployment.ts` read the deployment record
 * from disk on every request, `next.config.ts` rewrote `/api/*` and `/rpc` to the two upstream
 * services, and the chain's identity crossed into the browser as `NEXT_PUBLIC_*` inlined at
 * build time. All three need a server at request time, and the published console has none.
 *
 * So one file carries the same facts, the pages are client components, and this module is the
 * only place that knows where it lives and how to read it. What has NOT changed is the source:
 * the file is generated from the deployment record, and the generator re-reads its own output
 * and refuses to report success if an address disagrees.
 *
 * WHY THE URL IS BUILT FROM `NEXT_PUBLIC_BASE_PATH`
 *
 * A GitHub Pages project site is served from `/<repo>/`, so a request for `/api/config` would
 * leave the site entirely and 404 against the domain root. Next rewrites `<Link>` and the router
 * for `basePath`; it cannot rewrite a `fetch` written by hand. The base path is inlined at build
 * time (`next.config.ts` sets it), and in development it is empty -- one code path, both hosts.
 */

export interface RuntimeConfig {
  chainId: number;
  chainName: string;
  vault: `0x${string}`;
  asset: `0x${string}`;
  owner: `0x${string}` | null;
  deployBlock: number;
  /** The record's own note -- what this deployment is, in the deployer's words. */
  note: string | null;
  /** Where the record was read from, shown to the reader so the figure has a provenance. */
  recordPath: string;
  /** Where THIS PAGE sends its chain reads. Absolute: a wallet needs a URL, not a path. */
  rpcUrl: string;
  /** What `wallet_addEthereumChain` is told. Always the deployment's own endpoint. */
  walletRpcUrl: string;
  /**
   * The index service, or `null` when this page has no route to one.
   *
   * `null` is a value, not a gap. On a static host there is no proxy and no service, and the
   * panels say exactly that instead of reporting a failure of a service they never contacted.
   */
  indexApiUrl: string | null;
}

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

/** The absolute path of the generated config, on whatever host serves this page. */
export function runtimeConfigPath(): string {
  return `${BASE_PATH}/api/config`;
}

/**
 * Read the generated config.
 *
 * Validated here rather than at the first use: a config with no `vault` renders exactly like a
 * page whose chain is down, and those two need different fixes. Throwing a message that names
 * the missing field is the difference between a five-minute fix and an afternoon.
 */
export async function loadRuntimeConfig(fetchImpl: typeof fetch = fetch): Promise<RuntimeConfig> {
  const path = runtimeConfigPath();
  let response: Response;
  try {
    response = await fetchImpl(path, { cache: 'no-store' });
  } catch (cause) {
    throw new Error(`${path} could not be fetched: ${cause instanceof Error ? cause.message : String(cause)}`);
  }
  if (!response.ok) {
    throw new Error(`${path} answered ${response.status}. It is generated by scripts/build-runtime-config.mjs.`);
  }
  const raw = (await response.json()) as Partial<RuntimeConfig>;

  const problems: string[] = [];
  if (!/^0x[0-9a-fA-F]{40}$/.test(raw.vault ?? '')) problems.push(`vault is not an address: ${raw.vault}`);
  if (!/^0x[0-9a-fA-F]{40}$/.test(raw.asset ?? '')) problems.push(`asset is not an address: ${raw.asset}`);
  if (!Number.isInteger(raw.chainId)) problems.push(`chainId is not an integer: ${raw.chainId}`);
  if (!Number.isInteger(raw.deployBlock)) problems.push(`deployBlock is not a block number: ${raw.deployBlock}`);
  if (!/^https?:\/\//.test(raw.rpcUrl ?? '')) problems.push(`rpcUrl is not an absolute URL: ${raw.rpcUrl}`);
  if (raw.indexApiUrl !== null && !/^(https?:\/\/|\/)/.test(raw.indexApiUrl ?? '')) {
    problems.push(`indexApiUrl is neither null nor a URL/path: ${raw.indexApiUrl}`);
  }
  if (problems.length) {
    throw new Error(`${path} is not usable as a runtime config:\n  - ${problems.join('\n  - ')}`);
  }
  return raw as RuntimeConfig;
}

/**
 * An index-service URL, or `null` when there is no service to ask.
 *
 * `indexApiUrl` is an ORIGIN, not an endpoint prefix: the service paths already begin with
 * `/api`. So the same-origin value is `/` (which is what the dev config uses, and what
 * `next.config.ts` rewrites), and a hosted service would be `https://host:port`. Joining a base of
 * `/api` with a path of `/api/status` produces `/api/api/status`, which is why the distinction is
 * written down here instead of being assumed at each call site.
 *
 * One place decides how a service path is joined, so a caller cannot accidentally turn "there is
 * no service" into a request against this page's own origin -- which would answer 404 from the
 * static host and be reported as a broken service.
 */
export function indexApiUrlFor(config: RuntimeConfig, path: string): string | null {
  if (config.indexApiUrl === null) return null;
  const suffix = path.startsWith('/') ? path : `/${path}`;
  const base = config.indexApiUrl.replace(/\/+$/, ''); // '/' becomes '', which is the root
  if (/^https?:\/\//i.test(base)) return `${base}${suffix}`;
  // A same-origin base. On a project site the request must stay inside the project's directory,
  // so the build's base path is part of it.
  return `${BASE_PATH}${base}${suffix}`;
}
