/**
 * The runtime config the browser reads, written by `scripts/build-runtime-config.mjs`.
 *
 * WHY THIS REPLACES A SERVER-SIDE READ
 *
 * The console began as server components: `src/lib/deployment.ts` read the deployment record
 * from disk on every request, `next.config.ts` rewrote `/api/*` and `/rpc` to the two upstream
 * services, and the chain's identity crossed into the browser as `NEXT_PUBLIC_*` inlined at
 * build time. All three need a server at request time, and the published console has none.
 *
 * So one file carries the same facts, the pages are client components, and this module is the
 * only place that knows where it lives and how to read it. What has NOT changed is the source:
 * the file is generated from the deployment record, and the generator re-reads its own output
 * and refuses to report success if an address disagrees.
 *
 * WHY THE URL IS BUILT FROM `NEXT_PUBLIC_BASE_PATH`
 *
 * A GitHub Pages project site is served from `/<repo>/`, so a request for `/api/config` would
 * leave the site entirely and 404 against the domain root. Next rewrites `<Link>` and the router
 * for `basePath`; it cannot rewrite a `fetch` written by hand. The base path is inlined at build
 * time (`next.config.ts` sets it), and in development it is empty -- one code path, both hosts.
 */

export interface RuntimeConfig {
  chainId: number;
  chainName: string;
  vault: `0x${string}`;
  asset: `0x${string}`;
  owner: `0x${string}` | null;
  deployBlock: number;
  /** The record's own note -- what this deployment is, in the deployer's words. */
  note: string | null;
  /** Where the record was read from, shown to the reader so the figure has a provenance. */
  recordPath: string;
  /** Where THIS PAGE sends its chain reads. Absolute: a wallet needs a URL, not a path. */
  rpcUrl: string;
  /** What `wallet_addEthereumChain` is told. Always the deployment's own endpoint. */
  walletRpcUrl: string;
  /**
   * The index service, or `null` when this page has no route to one.
   *
   * `null` is a value, not a gap. On a static host there is no proxy and no service, and the
   * panels say exactly that instead of reporting a failure of a service they never contacted.
   */
  indexApiUrl: string | null;
  /**
   * Whether the index answers this page reads are a SNAPSHOT taken while it was being built.
   *
   * THE ONE THING THE CLIENT CANNOT WORK OUT FOR ITSELF. `indexApiUrl` says WHERE the answers
   * come from; it cannot say WHEN. A live service answers every request, and a directory of files
   * captured during the build answers every request too -- to the client the two are identical
   * right up until the numbers are stale. The published console serves the second
   * (`scripts/capture-index-snapshot.mjs` fills `public/api/`, the Pages workflow runs it before
   * `npm run build`), so the build states which one it produced and the panels label the source
   * with it.
   *
   * FALSE IN DEVELOPMENT, and false is the safe default: a page that says "live" when it is
   * reading a snapshot understates its own age, which is the failure mode this whole field
   * exists to prevent. The reverse (saying "snapshot" over a live service) only makes the page
   * more cautious than it needs to be.
   */
  indexSnapshot: boolean;
}

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

/** The absolute path of the generated config, on whatever host serves this page. */
export function runtimeConfigPath(): string {
  return `${BASE_PATH}/api/config`;
}

/**
 * Read the generated config.
 *
 * Validated here rather than at the first use: a config with no `vault` renders exactly like a
 * page whose chain is down, and those two need different fixes. Throwing a message that names
 * the missing field is the difference between a five-minute fix and an afternoon.
 */
export async function loadRuntimeConfig(fetchImpl: typeof fetch = fetch): Promise<RuntimeConfig> {
  const path = runtimeConfigPath();
  let response: Response;
  try {
    response = await fetchImpl(path, { cache: 'no-store' });
  } catch (cause) {
    throw new Error(`${path} could not be fetched: ${cause instanceof Error ? cause.message : String(cause)}`);
  }
  if (!response.ok) {
    throw new Error(`${path} answered ${response.status}. It is generated by scripts/build-runtime-config.mjs.`);
  }
  /*
   * A body that is not JSON is caught HERE rather than left to `response.json()`.
   *
   * The raw failure is undici's own `SyntaxError: Unexpected token '<', "<!doctype html>" is not
   * valid JSON`, which names neither the file nor the fact that this is a generated artefact.
   * The realistic cause is a static host answering a missing path with its 404 page -- so the
   * reader is looking at a config that was never generated, and the useful sentence says so.
   */
  let raw: Partial<RuntimeConfig>;
  try {
    raw = (await response.json()) as Partial<RuntimeConfig>;
  } catch (cause) {
    throw new Error(
      `${path} answered ${response.status} but not with JSON (${cause instanceof Error ? cause.message : String(cause)}). ` +
        'It is generated by scripts/build-runtime-config.mjs; a static host answers a missing path with an HTML page.',
    );
  }

  const problems: string[] = [];
  if (!/^0x[0-9a-fA-F]{40}$/.test(raw.vault ?? '')) problems.push(`vault is not an address: ${raw.vault}`);
  if (!/^0x[0-9a-fA-F]{40}$/.test(raw.asset ?? '')) problems.push(`asset is not an address: ${raw.asset}`);
  if (!Number.isInteger(raw.chainId)) problems.push(`chainId is not an integer: ${raw.chainId}`);
  if (!Number.isInteger(raw.deployBlock)) problems.push(`deployBlock is not a block number: ${raw.deployBlock}`);
  if (!/^https?:\/\//.test(raw.rpcUrl ?? '')) problems.push(`rpcUrl is not an absolute URL: ${raw.rpcUrl}`);
  if (raw.indexApiUrl !== null && !/^(https?:\/\/|\/)/.test(raw.indexApiUrl ?? '')) {
    problems.push(`indexApiUrl is neither null nor a URL/path: ${raw.indexApiUrl}`);
  }
  // Refused rather than defaulted, for the same reason as every other field here: `undefined` is
  // falsy, so a default would silently label a snapshot "live" -- the one direction of this flag
  // that understates how old the figures are. A config written before this field existed is
  // regenerated by `scripts/build-runtime-config.mjs`, which is one command.
  if (typeof raw.indexSnapshot !== 'boolean') {
    problems.push(`indexSnapshot is not a boolean: ${raw.indexSnapshot}`);
  }
  // A contradiction, not a gap: nothing is fetched at all when `indexApiUrl` is null, so a
  // snapshot cannot have been read from it.
  if (raw.indexSnapshot === true && raw.indexApiUrl === null) {
    problems.push('indexSnapshot is true but indexApiUrl is null, so there is no snapshot to have read');
  }
  if (problems.length) {
    throw new Error(`${path} is not usable as a runtime config:\n  - ${problems.join('\n  - ')}`);
  }
  return raw as RuntimeConfig;
}

/**
 * An index-service URL, or `null` when there is no service to ask.
 *
 * `indexApiUrl` is an ORIGIN, not an endpoint prefix: the service paths already begin with
 * `/api`. So the same-origin value is `/` (which is what the dev config uses, and what
 * `next.config.ts` rewrites), and a hosted service would be `https://host:port`. Joining a base of
 * `/api` with a path of `/api/status` produces `/api/api/status`, which is why the distinction is
 * written down here instead of being assumed at each call site.
 *
 * One place decides how a service path is joined, so a caller cannot accidentally turn "there is
 * no service" into a request against this page's own origin -- which would answer 404 from the
 * static host and be reported as a broken service.
 */
export function indexApiUrlFor(config: RuntimeConfig, path: string): string | null {
  if (config.indexApiUrl === null) return null;
  const suffix = path.startsWith('/') ? path : `/${path}`;
  const base = config.indexApiUrl.replace(/\/+$/, ''); // '/' becomes '', which is the root
  if (/^https?:\/\//i.test(base)) return `${base}${suffix}`;
  // A same-origin base. On a project site the request must stay inside the project's directory,
  // so the build's base path is part of it.
  return `${BASE_PATH}${base}${suffix}`;
}
