'use client';

import { useRuntimeConfig } from '@/app/providers';
import { VaultManager } from '@/components/VaultManager';

/**
 * `/vault/manage` -- the wallet page.
 *
 * WHY THIS USED TO BE SPLIT IN TWO
 *
 * The deployment record was a file on disk, and reading it was server work; the wallet is browser
 * state, and reading it is client work. So this file read the record and passed the three facts the
 * client could not obtain (`chainId`, `vault`, `asset`) down as props, and `VaultManager` did
 * everything else -- a split that also kept the address out of the client bundle.
 *
 * WHY IT IS ONE COMPONENT NOW
 *
 * The published console is a static export, so there is no server half. The address still is not in
 * the bundle: it arrives in `api/config`, which is generated from the same deployment record, read
 * at load time. The property the split was protecting -- a redeploy cannot leave the page talking to
 * the previous vault -- is unchanged, because the config is regenerated by the same build that
 * publishes the page.
 *
 * `useRuntimeConfig()` throws if it is used outside `Providers`, and `Providers` renders the
 * "could not start" screen when the config cannot be read. So a missing or partial record cannot
 * become a page that queries address zero and renders zeros as fact: it cannot become a page at all.
 *
 * WHAT WAS LOST, STATED RATHER THAN OMITTED: this file used to export `metadata` with a title and
 * description for the route. A client component cannot export `metadata` -- it is a server
 * construct -- so the title now comes from the layout, which is the same title every route had
 * before this one added its own. Putting it back means adding a server component wrapper purely to
 * re-export metadata for a static page, which is a page of indirection for a browser tab label.
 */
export default function ManagePage() {
  const runtime = useRuntimeConfig();

  return (
    <VaultManager
      // No cast and no check against a configured-chain list any more: the wagmi config is built
      // FROM this record (see `src/lib/wagmi.ts`), so there is exactly one chain and it is this
      // one. The old check existed because the config listed chains independently of the record,
      // which is a way for the two to disagree.
      chainId={runtime.chainId}
      vault={runtime.vault}
      // The asset is an address from the record. Its symbol and decimals are read from the chain
      // by the client, because those belong to the contract rather than to the deployment.
      asset={runtime.asset}
    />
  );
}
